apiVersion: fission.io/v1
kind: Package
metadata:
  name: hello-pkg-git
spec:
  deployment:
    checksum: { }
    type: url
    url: https://raw.githubusercontent.com/mstefantsiv/fission/main/specs/hello.py
  environment:
    name: python
    namespace: ""
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-05-12T16:47:50Z"

---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python-env
spec:
  builder:
    command: build
    container:
      name: ""
      resources: {}
    image: fission/python-builder:latest
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container:
      name: ""
      resources: {}
    image: fission/python-env
  version: 2

---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: env-func-git
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python-env
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hello-pkg-git
      namespace: ""
  requestsPerPod: 1
  resources: {}
